/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package point.of.sale;

import org.junit.Test;



import static org.junit.Assert.*;

public class AppTest {
    @Test 
    
    public void shouldAddEmployeeToPOS() {
    	HR testTable = new HR();
    	Employee newEmp = new Employee(403403, "Fry");
    	
    	
		
		int intialEmployees = testTable.getNumofEmployees();
		testTable.addEmployee(newEmp);
		int moreEmployees = testTable.getNumofEmployees();
		
		assertEquals(intialEmployees + 1, moreEmployees);
    	
    	
    	
    }
    
    @Test
    
    public void addMenuItemtoPOS() {
    	POS testTable = new POS();
    	MenuItems newItem = new MenuItems("1", "DBL CHS", 3.99);
    	
    	int intialItems = testTable.getNumofMenuItems();
    	testTable.addMenuItem(newItem);
    	int addedItems = testTable.getNumofMenuItems();
    	
    	assertEquals(intialItems + 1, addedItems);
    	
    	
    	
    	
    	
    }
}
