/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package point.of.sale;

import java.util.Scanner;

public class App {
  

    public static void main(String[] args) {
        Scanner input = new Scanner (System.in);
        
    	System.out.println("****************************************************************************");
    	System.out.println("                Welcome to the SnS Emergency POS System                     ");
    	System.out.println("****************************************************************************");
    	
    	
    	

    }
}
