/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package point.of.sale;

import java.util.Scanner;

public class App {
  

    public static void main(String[] args) {
        Scanner input = new Scanner (System.in);
        
        HR employeeRoster = new HR();
        employeeRoster.addEmployee(new Employee(100000, "Matt Fry"));
        
        
    	System.out.println("****************************************************************************");
    	System.out.println("                Welcome to the SnS Emergency POS System                     ");
    	System.out.println("****************************************************************************");
    	System.out.println("NOTICE: YOUR NORMAL POS HAS FAILED.  PLEASE CONTACT THE HELPDESK IMMEDIATELY!");
    	System.out.println("MOST POS FUNCTIONS CAN BE HANDLED THROUGH COMMAND LINE INPUT.  PLEASE SEE ");
    	System.out.println("THE MENU BELOW FOR A LIST OF OPTIONS.");
    	boolean posIsOn = true;
    	
    	while(posIsOn) {
    	System.out.println("*****************************************************************************");
    	System.out.println("                               MAIN MENU");
    	System.out.println("                           1.  Manager Functions");
    	System.out.println("                           2.  Add/Edit Orders Menu");
    	System.out.println("                           3.  Cash Out Open Checks");
    	System.out.println("                                                                              ");
    	System.out.println("******************************************************************************");
    	System.out.println("Select an Option:");
    	
    	int userOption = input.nextInt();
    	
    	switch(userOption) {
    	case 1://manager functions
    		
    		boolean mgrMenuIsOn = true;
    		
    		while (mgrMenuIsOn) {
    		System.out.println("*****************************************************************************");
        	System.out.println("                               MANAGER MENU");
        	System.out.println("                           1.  Hire/Borrow Employee");
        	System.out.println("                           2.  Terminate Employee");
        	System.out.println("                           3.  Update Employee Information");
        	System.out.println("                           4.  Return to Main Menu                           ");
        	System.out.println("*****************************************************************************");
        	System.out.println("Select an Option:");
    		int mgrOption = input.nextInt();
    		
    		
    		switch (mgrOption) {
    		case 1://Hire or borrow employee 
    			
    			System.out.println("*****************************************************************************");
    			System.out.println("                          ADD NEW EMPLOYEE                                   ");
    			System.out.println("  Enter the name of the Associate that needs to be added:  ");
    			String empName = input.next();
    			
    			
    			
    			int empID = 100000;
    			int checkPayrollEntries = employeeRoster.getNumofEmployees();
    			int newEmpID = empID + checkPayrollEntries;
    			
    			Employee newEmp = new Employee(newEmpID, empName);
    			
    			employeeRoster.addEmployee(newEmp);
    			
    			Employee confirmHire = employeeRoster.getEmployeeID(newEmpID);
    			
    			System.out.println("The following employee information has been added:");
    			System.out.println(confirmHire.employeeID() + "  " + confirmHire.employeeName());
    			input.next();
    			
    			break;
    			
    		case 2:// Terminate Employee
    		case 3://Update Employe3 Information
    		}
    		
    		
    		}
    	case 2://Add/Edit ORders
    		
    	case 3://Cash Out Orders
    	}//userOptionSwitch
    	}//while posIsOn

    	}//close main method
    }//close app class

